nome = input('Digite seu nome! ')
dia = input('Digite o dia que você nasceu ')
mes = input('Digite o mês que você nasceu ')
ano = input('Digite o ano que você nasceu ')
print('Oi, ', nome, 'você nasceu no dia ', dia , 'do mes de', mes , 'e do ano de ', ano)