nome = ('Diego Adler pereira Assunção')
print(nome[3:10])
print(nome.replace('Diego', 'Dr'))
print(nome.split())
dividido = nome.split() 
print(split) 
print([nome])
print(nome)
print(nome.upper().count('A'))
print(len(nome))
print(nome.find('Adler'))


curso = ('Curso em Video Python')
print(curso)
print(curso[9:21:2])
print(curso[:14])
print(curso[9:])
print(curso[9::3])
print(curso.split())